# Ejercicio

El ejercicio consiste en extraer datos de manera automatizada, realizarle las transformaciones necesarias y luego cargarlos en la base de datos ya creada. La idea sería que con una simple ejecución diaria de este código nuestra base de datos de MySQL se vea actualizada.

 - Carga la librería yfinance, ya que es la que contiene información diaria de los precios de la bolsa. 
 
 - Selecciona un ticker (código de empresa), por ejemplo 'MMM' y ejecuta este código para ver qué nos devuelve yfinance, analiza qué variables tenemos, cómo se llaman, qué formato tienen, qué parte de este dataframe nos interesaría, qué transformaciones necesitaría para encajar perfectamente en la tabla Stocks, que es la que vamos a actualizar diariamente
   ```
    dat = yf.Ticker('MMM')
    dat = dat.history(period='1d')
   ```
 - Crea una función extract(), que automatice esta llamada, una transform(), que ponga los formatos de las variables "en su sitio" y que ordene las variables tal y como las llamarás en la función definitiva load().

In [3]:
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Date, Float, Enum, ForeignKey

from sqlalchemy_utils import database_exists, create_database, drop_database

from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker

import pandas as pd
import datetime as datetime

import pymysql
import tqdm

#!pip install yfinance --upgrade --no-cache-dir
import yfinance as yf

In [14]:
dat = yf.Ticker('MMM')
dat = dat.history(period='1d')
dat

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-04-04 00:00:00-04:00,134.190002,135.312195,126.544998,127.870003,7396905,0.0,0.0

In [13]:
dat = dat.history(period='1d')
dat

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-04-04 00:00:00-04:00,134.190002,135.312195,126.544998,127.730003,7392489,0.0,0.0

## Activamos la conexión con MySQL

Y definimos de nuevo las clases de las tablas, ya que las necesitaremos igualmente

In [87]:
engine = create_engine('mysql+pymysql://root:MYSQL.passw0rd@localhost:3306/Stockify')
Base = declarative_base()

/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/3210753896.py:2: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [88]:
class Company(Base):
    __tablename__ = 'Company'
    company_code = Column(String(120),primary_key=True)
    security = Column(String(120))
    sec = Column(String(120))
    gics_sector = Column(String(120))
    gics_sub_industry = Column(String(120))
    heads_location = Column(String(120))
    start_date = Column(Date)
    cik = Column(String(120))
    founded = Column(String(120))

In [89]:
class Stocks(Base):
    __tablename__ = 'Stocks'
    stock_id = Column(Integer,primary_key=True)
    company_code = Column(String(120),ForeignKey("Company.company_code"))
    date = Column(Date)
    max_price = Column(Float)
    min_price = Column(Float)
    volume = Column(Float)
    close = Column(Float)
    open = Column(Float)

In [90]:
class user(Base):
    __tablename__ = 'User'
    user_id = Column(Integer,primary_key=True)
    user_name=Column(String(20))
    user_city=Column(String(120))

In [91]:
class transactions(Base):
    __tablename__ = 'Transactions'
    trx_id = Column(Integer,primary_key=True)
    user_id = Column(Integer,ForeignKey("User.user_id"))
    company_code = Column(String(120),ForeignKey("Company.company_code"))
    stock_id = Column(Integer,ForeignKey("Stocks.stock_id"))
    units = Column(Integer)

## Definición de las funciones

primeramente tenemos la lista tickers con los códigos de las empresas que vamos a querer actualizar a diario. A continuación define las 3 funciones.

In [92]:
Session = sessionmaker(bind=engine)
session = Session()

In [ ]:
# Listado de los tickers que hay en la carga de datos que hicimos a través de los csv. Vamos a iterar sobre ellos para ver sus
# precios a día de hoy. Algunos ya no existen. 
ticker_list = [
    "AAL", "AAP", "AAPL", "ABBV", "ABC", "ABMD", "ABT", "ACN", "ADBE", "ADI", "ADM", 
    "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG", "AKAM", "ALB", 
    "ALGN", "ALK", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AME", "AMGN", "AMP", "AMT", 
    "AMZN", "ANET", "ANSS", "ANTM", "AON", "AOS", "APA", "APD", "APH", "APTV", "ARE", 
    "ATO", "ATVI", "AVB", "AVGO", "AVY", "AWK", "AXP", "AZO", "BA", "BAC", "BAX", 
    "BBWI", "BBY", "BDX", "BEN", "BF.B", "BIIB", "BIO", "BK", "BKNG", "BKR", "BLK", 
    "BLL", "BMY", "BR", "BRK.B", "BRO", "BSX", "BWA", "BXP", "C", "CAG", "CAH", 
    "CARR", "CAT", "CB", "CBOE", "CBRE", "CCI", "CCL", "CDAY", "CDNS", "CDW", "CE", 
    "CEG", "CERN", "CF", "CFG", "CHD", "CHRW", "CHTR", "CI", "CINF", "CL", "CLX", 
    "CMA", "CMCSA", "CME", "CMG", "CMI", "CMS", "CNC", "CNP", "COF", "COO", "COP", 
    "COST", "CPB", "CPRT", "CRL", "CRM", "CSCO", "CSX", "CTAS", "CTLT", "CTRA", 
    "CTSH", "CTVA", "CTXS", "CVS", "CVX", "CZR", "D", "DAL", "DD", "DE", "DFS", 
    "DG", "DGX", "DHI", "DHR", "DIS", "DISCA", "DISCK", "DISH", "DLR", "DLTR", "DOV", 
    "DOW", "DPZ", "DRE", "DRI", "DTE", "DUK", "DVA", "DVN", "DXC", "DXCM", "EA", 
    "EBAY", "ECL", "ED", "EFX", "EIX", "EL", "EMN", "EMR", "ENPH", "EOG", "EPAM", 
    "EQIX", "EQR", "ES", "ESS", "ETN", "ETR", "ETSY", "EVRG", "EW", "EXC", "EXPD", 
    "EXPE", "EXR", "F", "FANG", "FAST", "FB", "FBHS", "FCX", "FDS", "FDX", "FE", 
    "FFIV", "FIS", "FISV", "FITB", "FLT", "FMC", "FOX", "FOXA", "FRC", "FRT", "FTNT", 
    "FTV", "GD", "GE", "GILD", "GIS", "GL", "GLW", "GM", "GNRC", "GOOG", "GOOGL", 
    "GPC", "GPN", "GRMN", "GS", "GWW", "HAL", "HAS", "HCA", "HD", "HES", "HIG", 
    "HII", "HLT", "HOLX", "HON", "HPE", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUM", 
    "HWM", "IBM", "ICE", "IDXX", "IEX", "IFF", "ILMN", "INCY", "INTC", "INTU", "IP", 
    "IPG", "IPGP", "IQV", "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "J", "JBHT", 
    "JCI", "JKHY", "JNJ", "JNPR", "JPM", "K", "KEY", "KEYS", "KIM", "KLAC", "KMB", 
    "KMI", "KMX", "KO", "KR", "L", "LDOS", "LEN", "LH", "LHX", "LIN", "LKQ", "LLY", 
    "LMT", "LNC", "LNT", "LOW", "LRCX", "LUMN", "LUV", "LVS", "LW", "LYB", "LYV", 
    "MA", "MAA", "MAR", "MAS", "MCD", "MCHP", "MCK", "MCO", "MDLZ", "MDT", "MET", 
    "MGM", "MHK", "MKC", "MKTX", "MLM", "MMC", "MMM", "MNST", "MO", "MOH", "MOS", 
    "MPC", "MPWR", "MRK", "MRNA", "MRO", "MS", "MSCI", "MSFT", "MSI", "MTB", "MTCH", 
    "MTD", "MU", "NCLH", "NDAQ", "NDSN", "NEE", "NEM", "NFLX", "NI", "NKE", "NLOK", 
    "NLSN", "NOC", "NOW", "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NVR", "NWL", 
    "NWS", "NWSA", "NXPI", "O", "ODFL", "OGN", "OKE", "OMC", "ORCL", "ORLY", "OTIS", 
    "OXY", "PARA", "PAYC", "PAYX", "PBCT", "PCAR", "PEAK", "PEG", "PENN", "PEP", 
    "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PKI", "PLD", "PM", "PNC", "PNR", 
    "PNW", "POOL", "PPG", "PPL", "PRU", "PSA", "PSX", "PTC", "PVH", "PWR", "PXD", 
    "PYPL", "QCOM", "QRVO", "RCL", "RE", "REG", "REGN", "RF", "RHI", "RJF", "RL", 
    "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "SBAC", "SBNY", "SBUX", "SCHW", 
    "SEDG", "SEE", "SHW", "SIVB", "SJM", "SLB", "SNA", "SNPS", "SO", "SPG", "SPGI", 
    "SRE", "STE", "STT", "STX", "STZ", "SWK", "SWKS", "SYF", "SYK", "SYY", "T", 
    "TAP", "TDG", "TDY", "TECH", "TEL", "TER", "TFC", "TFX", "TGT", "TJX", "TMO", 
    "TMUS", "TPR", "TRMB", "TROW", "TRV", "TSCO", "TSLA", "TSN", "TT", "TTWO", "TWTR", 
    "TXN", "TXT", "TYL", "UA", "UAA", "UAL", "UDR", "UHS", "ULTA", "UNH", "UNP", 
    "UPS", "URI", "USB", "V", "VFC", "VLO", "VMC", "VNO", "VRSK", "VRSN", "VRTX", 
    "VTR", "VTRS", "VZ", "WAB", "WAT", "WBA", "WDC", "WEC", "WELL", "WFC", "WM", 
    "WMT", "XOM", "XRAY", "XYL", "YUM", "ZBH", "ZBRA", "ZION", "ZTS"
]

In [ ]:
# This doesn't work if there's a delisted ticker in ticker_list. For the ETL to work, the load needs to skip delisted tickers

# def extract1(ticker_list, period='1d'):
#     df = pd.DataFrame([])  # Creamos dataframe vacío
#     for t in ticker_list:
#         # llamada a los datos para cada empresa
#         ticker = yf.Ticker(t)
#         ticker_data = ticker.history(period=period)
#         # Añadimos columna con el ticker para identificar los datos
#         ticker_data['Ticker'] = t
#         # union con el histórico
#         df = pd.concat([df, ticker_data])
#     return df

In [ ]:
# new extract function that skips delisted tickers

def extract(ticker_list, period='1d'):
    df = pd.DataFrame([])  # Create empty DataFrame
    for t in ticker_list:
        try:
            # Get the stock data for each ticker
            ticker = yf.Ticker(t)
            ticker_data = ticker.history(period=period)
            
            # Check if ticker data is empty
            if ticker_data.empty:
                print(f"Warning: {t} possibly delisted; no data found.")
                continue  # Skip the current ticker if no data is found
            
            # Add the ticker column to identify the data
            ticker_data['Ticker'] = t
            
            # Append the data to the main DataFrame
            df = pd.concat([df, ticker_data])

        except Exception as e:
            # Handle any other exceptions (e.g., network issues, invalid tickers)
            print(f"Error fetching data for {t}: {e}")
            continue  # Skip this ticker and move to the next one

    return df

In [113]:
result_df = extract(ticker_list, period='1d')

$BF.B: possibly delisted; no price data found  (period=1d)

Warning: BF.B possibly delisted; no data found.

$BLL: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: BLL possibly delisted; no data found.

$BRK.B: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: BRK.B possibly delisted; no data found.

$CDAY: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: CDAY possibly delisted; no data found.

$CERN: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: CERN possibly delisted; no data found.

$CTLT: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: CTLT possibly delisted; no data found.

$CTXS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: CTXS possibly delisted; no data found.

In [114]:
result_df.head(15)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker
Date,,,,,,,,
2025-04-04 00:00:00-04:00,3792.719971,3845.100098,3652.219971,3653.239990,209900,0.00,0.0,AZO
2025-04-04 00:00:00-04:00,143.300003,146.000000,132.789993,136.589996,22254300,0.00,0.0,BA
2025-04-04 00:00:00-04:00,35.290001,35.790001,33.669998,34.389999,107718100,0.00,0.0,BAC
2025-04-04 00:00:00-04:00,30.730000,31.190001,28.700001,28.790001,5994900,0.00,0.0,BAX
2025-04-04 00:00:00-04:00,26.809999,27.799999,25.410000,27.290001,9961100,0.00,0.0,BBWI
2025-04-04 00:00:00-04:00,59.259998,62.270000,57.340000,60.439999,8428700,0.00,0.0,BBY
2025-04-04 00:00:00-04:00,219.520004,220.449997,204.949997,207.339996,6623800,0.00,0.0,BDX
2025-04-04 00:00:00-04:00,17.680000,18.240000,17.190001,17.510000,11448300,0.00,0.0,BEN
2025-04-04 00:00:00-04:00,129.220001,129.949997,122.769997,122.980003,3089900,0.00,0.0,BIIB
2025-04-04 00:00:00-04:00,230.520004,231.309998,221.179993,225.600006,766900,0.00,0.0,BIO
2025-04-04 00:00:00-04:00,77.040001,78.730003,72.930000,73.309998,6696700,0.00,0.0,BK
2025-04-04 00:00:00-04:00,4322.220215,4513.250000,4284.020020,4284.020020,508500,0.00,0.0,BKNG
2025-04-04 00:00:00-04:00,39.290001,39.680000,35.279999,35.410000,20972300,0.00,0.0,BKR
2025-04-04 00:00:00-04:00,852.880005,860.520020,811.159973,822.619995,1613900,0.00,0.0,BLK
2025-04-04 00:00:00-04:00,56.820000,57.169998,54.720001,55.299999,14648700,0.62,0.0,BMY

In [35]:
result_df.index

DatetimeIndex(['2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               ...
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00',
               '2025-04-04 00:00:00-04:00', '2025-04-04 00:00:00-04:00'],
              dtype='datetime64[ns, America/New_York]', name='Date', length=463, freq=None)

In [115]:
def transform(df):
    df_transform = df.copy()
    df_transform = df_transform.dropna()
    
    # Realiza las transformaciones necesarias

    #by default Yahoo finance sets Date as Index as this is time series data
    # Convert the Date index to the desired format
    df_transform.index = df_transform.index.strftime('%Y-%m-%d')
    
    # Reset index to make Date a column and rename it
    df_transform = df_transform.reset_index()
    df_transform = df_transform.rename(columns={'index': 'Date'})
    
    return df_transform

In [116]:
result_transform_df = transform(result_df)

In [110]:
result_transform_df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Ticker', 'Adj Close'],
      dtype='object')

In [117]:
result_transform_df.head(50)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker
0,2025-04-04,3792.719971,3845.100098,3652.219971,3653.239990,209900,0.00,0.0,AZO
1,2025-04-04,143.300003,146.000000,132.789993,136.589996,22254300,0.00,0.0,BA
2,2025-04-04,35.290001,35.790001,33.669998,34.389999,107718100,0.00,0.0,BAC
3,2025-04-04,30.730000,31.190001,28.700001,28.790001,5994900,0.00,0.0,BAX
4,2025-04-04,26.809999,27.799999,25.410000,27.290001,9961100,0.00,0.0,BBWI
5,2025-04-04,59.259998,62.270000,57.340000,60.439999,8428700,0.00,0.0,BBY
6,2025-04-04,219.520004,220.449997,204.949997,207.339996,6623800,0.00,0.0,BDX
7,2025-04-04,17.680000,18.240000,17.190001,17.510000,11448300,0.00,0.0,BEN
8,2025-04-04,129.220001,129.949997,122.769997,122.980003,3089900,0.00,0.0,BIIB
9,2025-04-04,230.520004,231.309998,221.179993,225.600006,766900,0.00,0.0,BIO
10,2025-04-04,77.040001,78.730003,72.930000,73.309998,6696700,0.00,0.0,BK
11,2025-04-04,4322.220215,4513.250000,4284.020020,4284.020020,508500,0.00,0.0,BKNG
12,2025-04-04,39.290001,39.680000,35.279999,35.410000,20972300,0.00,0.0,BKR
13,2025-04-04,852.880005,860.520020,811.159973,822.619995,1613900,0.00,0.0,BLK
14,2025-04-04,56.820000,57.169998,54.720001,55.299999,14648700,0.62,0.0,BMY
15,2025-04-04,235.479996,236.130005,224.699997,225.039993,740600,0.00,0.0,BR
16,2025-04-04,122.389999,124.139999,114.720001,115.010002,2809400,0.00,0.0,BRO
17,2025-04-04,94.730003,95.889999,89.650002,89.699997,22572300,0.00,0.0,BSX
18,2025-04-04,26.250000,26.459999,24.660000,25.889999,3671800,0.00,0.0,BWA
19,2025-04-04,61.220001,61.900002,58.880001,60.419998,2530800,0.00,0.0,BXP
20,2025-04-04,60.250000,60.419998,56.310001,58.130001,51688100,0.00,0.0,C
21,2025-04-04,26.700001,27.680000,26.530001,26.680000,11256700,0.00,0.0,CAG
22,2025-04-04,134.479996,136.210007,128.770004,129.630005,3779400,0.00,0.0,CAH
23,2025-04-04,58.900002,59.099998,55.869999,57.180000,6933800,0.00,0.0,CARR
24,2025-04-04,285.000000,294.290009,281.500000,288.079987,7216000,0.00,0.0,CAT
25,2025-04-04,297.220001,299.269989,279.559998,280.679993,3195300,0.00,0.0,CB
26,2025-04-04,227.000000,230.350006,213.919998,215.089996,1914300,0.00,0.0,CBOE
27,2025-04-04,118.300003,120.879997,114.459999,118.080002,2543400,0.00,0.0,CBRE
28,2025-04-04,108.680000,109.000000,100.800003,100.980003,4772500,0.00,0.0,CCI
29,2025-04-04,16.490000,16.740000,15.610000,16.500000,39801900,0.00,0.0,CCL
30,2025-04-04,243.529999,246.220001,232.369995,232.880005,4201700,0.00,0.0,CDNS
31,2025-04-04,149.699997,149.699997,141.800003,144.490005,4384200,0.00,0.0,CDW
32,2025-04-04,45.320000,45.320000,39.619999,40.990002,5314500,0.00,0.0,CE
33,2025-04-04,180.070007,182.990005,165.080002,170.960007,9348100,0.00,0.0,CEG
34,2025-04-04,78.459999,78.459999,72.080002,73.070000,4001500,0.00,0.0,CF
35,2025-04-04,34.310001,34.895000,32.599998,34.270000,8827700,0.00,0.0,CFG
36,2025-04-04,111.680000,113.910004,105.870003,106.089996,3154300,0.00,0.0,CHD
37,2025-04-04,93.269997,94.230003,90.830002,90.940002,1524700,0.00,0.0,CHRW
38,2025-04-04,365.000000,368.920013,337.540009,338.290009,1834000,0.00,0.0,CHTR
39,2025-04-04,336.269989,343.910004,321.000000,322.399994,3801000,0.00,0.0,CI
40,2025-04-04,141.610001,142.490005,130.720001,131.690002,1339000,0.00,0.0,CINF
41,2025-04-04,96.949997,97.730003,91.320000,91.660004,7434400,0.00,0.0,CL
42,2025-04-04,148.720001,150.839996,143.309998,143.860001,2292900,0.00,0.0,CLX
43,2025-04-04,51.080002,52.130001,48.990002,51.619999,3419000,0.00,0.0,CMA
44,2025-04-04,34.930000,35.349998,33.340000,33.380001,37311600,0.00,0.0,CMCSA
45,2025-04-04,269.450012,273.420013,254.190002,254.460007,5818900,0.00,0.0,CME
46,2025-04-04,48.790001,49.279999,46.779999,47.290001,17905000,0.00,0.0,CMG
47,2025-04-04,285.380005,286.589996,273.000000,277.619995,1466000,0.00,0.0,CMI
48,2025-04-04,76.379997,76.379997,72.389999,72.690002,4394600,0.00,0.0,CMS
49,2025-04-04,64.260002,65.900002,61.880001,61.930000,8030200,0.00,0.0,CNC

In [ ]:
def load(ticker_list, period, table):
    df = extract(ticker_list, period)  # Extract data
    df_transform = transform(df)  # Transform data
    
    # Loop through each row in the transformed DataFrame
    for i, val in enumerate(df_transform.values):
        if table == 'Stocks':
            rec = Stocks(
                company_code = val[8],
                date = val[0],
                max_price = val[2],
                min_price = val[3],
                volume = val[5],
                close = val[4],
                open = val[1]
            )
            
            # Print out the record before adding to session
            print(f"Inserting into Stocks: {rec}")
        
        # Add the record to the session
        session.add(rec)
    
    # Commit the transaction to save the data
    try:
        session.commit()
        print("Data successfully committed to the Stocks table.")
    except Exception as e:
        session.rollback()
        print(f"Error during commit: {e}. Rollback performed.")

## Insertamos los datos

Llama a `load()` para que se complete el proceso ETL.

Ten cuidado porque si la acción no queda completamente realizada, porque dé error por ejemplo, habrá que hacer `rollback()`, para revertir lo que se quedó sin completar

In [119]:
#define the ETL function

def ETL(ticker_list, period='1d', table='Stocks'):
    try:
        # Call the load function to perform the ETL process and insert data
        load(ticker_list, period, table)
        # Commit the transaction to save the changes if no errors occurred
        session.commit()
        print("Data successfully inserted into the 'Stocks' table.")
    
    except Exception as e:
        # If any error occurs, roll back the transaction to prevent incomplete data insertion
        session.rollback()
        print(f"Error occurred: {e}. The transaction has been rolled back.")

In [ ]:
#call the ETL function
period = '1d'
table = 'Stocks'

ETL(ticker_list, period, table)

$BF.B: possibly delisted; no price data found  (period=1d)

Warning: BF.B possibly delisted; no data found.

$BLL: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: BLL possibly delisted; no data found.

$BRK.B: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: BRK.B possibly delisted; no data found.

$CDAY: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: CDAY possibly delisted; no data found.

$CERN: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: CERN possibly delisted; no data found.

$CTLT: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: CTLT possibly delisted; no data found.

$CTXS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: CTXS possibly delisted; no data found.
Inserting into Stocks: <__main__.Stocks object at 0x1280d2a80>
Inserting into Stocks: <__main__.Stocks object at 0x123ea7920>
Inserting into Stocks: <__main__.Stocks object at 0x1231a0500>
Inserting into Stocks: <__main__.Stocks object at 0x1231a16a0>
Inserting into Stocks: <__main__.Stocks object at 0x1231a0ef0>
Inserting into Stocks: <__main__.Stocks object at 0x1289a0920>
Inserting into Stocks: <__main__.Stocks object at 0x1258a9eb0>
Inserting into Stocks: <__main__.Stocks object at 0x1258a9bb0>
Inserting into Stocks: <__main__.Stocks object at 0x127d3a660>
Inserting into Stocks: <__main__.Stocks object at 0x127d3a330>
Inserting into Stocks: <__main__.Stocks object at 0x127d3a900>
Inserting into Stocks: <__main__.Stocks object at 0x127d3aa50>
Inserting into Stocks: <__main__.Stocks object at 0x127d3ac30>
Inserting into Stocks: <__main__.Stocks object at 0x1232eb410>
Inserting into Stocks: <__main__.Stocks object at 0x1288041a0>
Inserting into Stocks: <__main__.Stocks object at 0x128806ff0>
Inserting into Stocks: <__main__.Stocks object at 0x12789dd90>
Inserting into Stocks: <__main__.Stocks object at 0x12789dbe0>
Inserting into Stocks: <__main__.Stocks object at 0x12789daf0>
Inserting into Stocks: <__main__.Stocks object at 0x128301c40>
Inserting into Stocks: <__main__.Stocks object at 0x128300aa0>
Inserting into Stocks: <__main__.Stocks object at 0x128301c70>
Inserting into Stocks: <__main__.Stocks object at 0x1287600b0>
Inserting into Stocks: <__main__.Stocks object at 0x12375d400>
Inserting into Stocks: <__main__.Stocks object at 0x1239cc6b0>
Inserting into Stocks: <__main__.Stocks object at 0x1239ce390>
Inserting into Stocks: <__main__.Stocks object at 0x12870b500>
Inserting into Stocks: <__main__.Stocks object at 0x12870ad80>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf1d0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf0b0>
Inserting into Stocks: <__main__.Stocks object at 0x1232ccf80>
Inserting into Stocks: <__main__.Stocks object at 0x1232ce150>
Inserting into Stocks: <__main__.Stocks object at 0x1232ce450>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf2c0>
Inserting into Stocks: <__main__.Stocks object at 0x1232ce660>
Inserting into Stocks: <__main__.Stocks object at 0x1232ccce0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf800>
Inserting into Stocks: <__main__.Stocks object at 0x1232ce4e0>
Inserting into Stocks: <__main__.Stocks object at 0x1232ce570>
Inserting into Stocks: <__main__.Stocks object at 0x1232cfe30>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf350>
Inserting into Stocks: <__main__.Stocks object at 0x1232cdee0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cdbb0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cec60>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf380>
Inserting into Stocks: <__main__.Stocks object at 0x1232cfef0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cd190>
Inserting into Stocks: <__main__.Stocks object at 0x1232cee70>
Inserting into Stocks: <__main__.Stocks object at 0x1232cdfd0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cff50>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf8f0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cdd00>
Inserting into Stocks: <__main__.Stocks object at 0x1232cc620>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf200>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf290>
Inserting into Stocks: <__main__.Stocks object at 0x1232cd250>
Inserting into Stocks: <__main__.Stocks object at 0x1232cd100>
Inserting into Stocks: <__main__.Stocks object at 0x1232cd940>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf260>
Inserting into Stocks: <__main__.Stocks object at 0x1232ceb70>
Inserting into Stocks: <__main__.Stocks object at 0x1232ceab0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cce60>
Inserting into Stocks: <__main__.Stocks object at 0x1232ce2d0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cc230>
Inserting into Stocks: <__main__.Stocks object at 0x1232cfc20>
Inserting into Stocks: <__main__.Stocks object at 0x1232ceff0>
Inserting into Stocks: <__main__.Stocks object at 0x1232cf8c0>
Inserting into Stocks: <__main__.Stocks object at 0x1232ccec0>
Data successfully committed to the Stocks table.
Data successfully inserted into the 'Stocks' table.